"""
    LatticeSpaceGroupsSymBasisExt

Lets SymBasis.jl's spatial symmetry specifications be constructed straight from a lattice.

`SymBasis.Translational`, `SymBasis.SpatialReflection`, and `SymBasis.Rotational` each take a
single generator permutation and derive the cyclic group from it. Supplying that permutation by
hand only ever works for a one-dimensional chain — `mod1.((1:N) .+ 1, N)` and nothing else. This
extension derives it from the lattice geometry instead, so the same code works on a kagome
torus as on a chain.
"""
module LatticeSpaceGroupsSymBasisExt

using LatticeSpaceGroups
using LatticeSpaceGroups: Lattice, TOL_DIGITS

# `import`, not `using`: these constructors are being extended with new methods, and `using`
# would define shadowing functions in this module instead.
import SymBasis: Translational, SpatialReflection, Rotational

"""
    Translational(k, lattice; axis=1, cells=1)

Translational symmetry with momentum number `k`, generated by translating `lattice` by `cells`
primitive cells along `axis`.

# Example
```julia
lat = build(Hypercube([8], 1.0; periodic=[true]))
sg = sym(Translational(0, lat), dof_object(Spin(1 // 2)))
```
"""
function Translational(
    k::Integer, lattice::Lattice; axis::Integer=1, cells::Integer=1,
    tol_digits::Integer=TOL_DIGITS
)
    perm = translation_permutation(lattice, axis; cells=cells, tol_digits=tol_digits)
    return Translational(k, perm)
end

"""
    SpatialReflection(p, lattice; axis=1)

Reflection symmetry with parity `p` (either `1` or `-1`), generated by the reflection of
`lattice` that reverses `axis`.

The mirror plane is placed wherever the lattice actually admits one, which is not generally the
coordinate origin — on an open chain it is the midpoint, and on a lattice with a multi-site unit
cell it is fixed by the site offsets.
"""
function SpatialReflection(
    p::Integer, lattice::Lattice; axis::Integer=1, tol_digits::Integer=TOL_DIGITS
)
    perm = reflection_permutation(lattice, axis; tol_digits=tol_digits)
    return SpatialReflection(p, perm)
end

"""
    Rotational(r, lattice; index=1)

Rotational symmetry with rotation number `r`, generated by the `index`-th proper rotation of
`lattice` as returned by `rotation_permutations`.

The rotations are not returned in any physically meaningful order, so `index` selects among
them positionally. Inspect `rotation_permutations(lattice)` to see what is available; a lattice
with no non-trivial proper rotation gives an empty list, and this constructor then throws.
"""
function Rotational(
    r::Integer, lattice::Lattice; index::Integer=1, tol_digits::Integer=TOL_DIGITS
)
    perms = rotation_permutations(lattice; tol_digits=tol_digits)
    if isempty(perms)
        throw(ArgumentError("this lattice has no non-trivial proper rotation"))
    end
    if !(1 <= index <= length(perms))
        throw(ArgumentError(
            "index $index is out of range: this lattice has $(length(perms)) rotation(s)"
        ))
    end
    return Rotational(r, perms[index])
end

end # module LatticeSpaceGroupsSymBasisExt
